import type { Metadata, Viewport } from "next";
import { Bricolage_Grotesque, Caveat, Hanken_Grotesk } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import { CartProvider } from "@/cart/CartContext";
import { SITE, SITE_URL } from "@/lib/site";
import { DELIVERY } from "@/lib/shipping";
import "./globals.css";

const bricolage = Bricolage_Grotesque({
  subsets: ["latin"],
  variable: "--font-bricolage",
  display: "swap",
  weight: ["400", "600", "700", "800"],
});

const caveat = Caveat({
  subsets: ["latin"],
  variable: "--font-caveat",
  display: "swap",
  weight: ["500", "700"],
});

const hanken = Hanken_Grotesk({
  subsets: ["latin"],
  variable: "--font-hanken",
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: "PUCCII Swim: Endless Summer Collection",
  description: `Bold. Beautiful. Unapologetic. Shop the Endless Summer drop. Four swim styles, endless colors, $39 each. ${DELIVERY.shipping.freeLabel}, or free pickup in El Paso.`,
  keywords: ["PUCCII Swim", "swimwear", "bikini", "shop", "Endless Summer", "Mya Mercedes"],
  openGraph: {
    title: "PUCCII Swim: Endless Summer Collection",
    description:
      "Shop the Endless Summer drop. Four styles, endless colors, $39 each. Bold. Beautiful. Unapologetic.",
    url: SITE_URL,
    siteName: SITE.name,
    // OG image is generated by app/opengraph-image.tsx (file convention).
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "PUCCII Swim: Endless Summer Collection",
    description: "Shop the Endless Summer drop. $39 every set.",
  },
  icons: {
    icon: [{ url: "/favicon.svg", type: "image/svg+xml" }],
    apple: "/favicon.svg",
  },
};

export const viewport: Viewport = {
  themeColor: "#F06BB0",
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${bricolage.variable} ${caveat.variable} ${hanken.variable}`}>
      <body>
        <CartProvider>{children}</CartProvider>
        <Analytics />
      </body>
    </html>
  );
}
